services:
  - type: web
    name: winternet-quiz
    runtime: docker
    repo: https://github.com/yanivbahalul/WinterNET
    branch: main
    dockerfilePath: ./Dockerfile
    env:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: 8080
